import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import { getAllPosts, getPostDataBySlug } from "./api";

type FrontMatter = {
  path: string;
  title: string;
  date: string;
  description: string;
};

type PostData = {
  frontMatter: FrontMatter;
  content: string;
};

type Props = {
  posts: PostData[];
};

export default function Home(props: Props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>ibulog</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
        <link
          rel="icon"
          href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text x=%2250%%22 y=%2250%%22 style=%22dominant-baseline:central;text-anchor:middle;font-size:90px;%22>😸</text></svg>"
        ></link>
        {/* Safari / IE */}
        <link
          rel="icon alternate"
          type="image/png"
          href="https://twemoji.maxcdn.com/v/13.0.2/72x72/1f638.png"
        />
      </Head>

      <main className={styles.main}>
        <h1 className="text-lg font-semibold">ibulog</h1>
        {props.posts.map(({ frontMatter }, index) => {
          const { path, title, date, description } = frontMatter;
          return (
            <PostCard
              key={index}
              title={title}
              path={path}
              date={date}
              description={description}
            />
          );
        })}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

const PostCard = ({ path, title, date, description }: FrontMatter) => {
  return (
    <div className="w-48 m-2 p-4 border-2">
      <Link href={path}>
        <a className="text-lg">{title}</a>
      </Link>
      <p className="text-xs">{date}</p>
      <p className="text-sm">{description}</p>
    </div>
  );
};

export async function getStaticProps() {
  const posts = getAllPosts().map((path) => {
    return getPostDataBySlug(path);
  });
  return { props: { posts: posts } };
}
